### ISSUE TITLE
集市没有获取到 README

### ISSUE THREAD

**Issue by TCOTC** [iamqiz/siyuan-plugin-add-shortcut-to-topbar#1]
![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/ba8016ce-3e46-49ab-b5bf-10b1ce9c7c03)

**Comment by iamqiz** [comment]
貌似是因为我在plugin.json里声明了中文readme,但没有上传到github ,所以思源没找到那个文件

**Comment by TCOTC** [comment]
虽然看上去不是中文 README 的问题，但还是加上吧。然后重新打包发个版看看

**Comment by iamqiz** [comment]
我测试过了,报错的时候获取的readme是中文版的, 当我改成readme.md时就能获取成功了
我觉得可以优化下思源,在获取非默认readme失败时,回退到默认readme.md,如果还获取不到,再报错

**Comment by iamqiz** [comment]
解决了
