### ISSUE TITLE
需求

### ISSUE THREAD

**Issue by yanyu2015** [iamqiz/siyuan-plugin-add-shortcut-to-topbar#2]
首先非常感谢这个使用的插件，使用后有两个问题想请教下：
- 我插入后的图标，现实在了顶部的工具栏：
![Uploading image.png…]()
这是合理的不？是否最好是在笔记的编辑工具栏呢？
![Uploading image.png…]()

- 另外提了个需求，能不能直接修改笔记的编辑工具栏，我想把很多日常用不到的按钮都取消掉，最后换成自定义的按钮

**Comment by iamqiz** [comment]
你的图没上传成功
你说的工具栏是下面这个吗？
![Clip_2024-05-03_13-48-57](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/48077521/7bcbb22d-3e94-494e-aa97-e919fb2eb3f6)

我这个插件设计是在顶栏添加图标，用于触发按键，不专门处理文本
笔记里的工具栏主要是处理选中的文本，
你说的第二点中取消按钮应该能实现， 换成自定义的按钮，如果是换成思源本来就提供的，那也好办，换成本来没有的，那需要自己专门写插件实现

**Comment by yanyu2015** [comment]
抱歉，不知道为啥我上传图形没成功，我讲的就是你截图中的这个意思。
因为如果是放在顶部，其实目前我都感觉顶部的感觉太多了，只想选择性展示一些，而顶部工具栏的按钮，其实更多应该提供一些全局性的功能，而笔记编辑工具栏，主要是对笔记内容进行设置，当然，可能是因为我设置的按钮刚好是插入引用，所以我才这么想。既然这样的。
那么能不能实现下对现有的顶部工具栏和笔记工具栏实现**自定义显示哪些按钮**呢？

**Comment by iamqiz** [comment]
实现 自定义显示哪些按钮 应该可以， 我得有空研究一下
你说的 插入引用 对应的快捷键名字叫啥？

**Comment by yanyu2015** [comment]
那个是我自定义的快捷键，用的“文献引用”这个插件，应该不是你理解的引用

**Comment by iamqiz** [comment]
哦，只要有对应的快捷键 就好办

**Comment by iamqiz** [comment]
@yanyu2015  v1.1.0版本实现了,改了很多,先把旧版卸载了再安装

**Comment by yanyu2015** [comment]
已经用上了，感觉我的需求差不多是完美实现了！谢谢佬！
