### ISSUE TITLE
无法隐藏自带图标、排序无效

### ISSUE THREAD

**Issue by TCOTC** [iamqiz/siyuan-plugin-add-shortcut-to-topbar#3]
用新工作空间测试，确认配置保存了并且重启思源：

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/976db423-3802-4f22-a0da-3e8a8fa7993d)

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/503b485d-ff09-4e8c-9f95-3fa25e08e318)

**Comment by iamqiz** [comment]
想起来了,对于顶栏自带的工具图标,忘了实现禁用功能了,
排序的话,先拖动每个配置上下移动,最后需要保存再刷新才行

**Comment by TCOTC** [comment]
> 先拖动每个配置上下移动,最后需要保存再刷新

很奇怪，这个排序跟实际的不同：

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/2b440702-70c7-4094-8968-5943d9e50ab9)

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/b108bd87-99ab-4633-b912-aea0259246c0)

**Comment by iamqiz** [comment]
1.1.2 应该修复了

**Comment by TCOTC** [comment]
确认修复了，非常感谢！
