### ISSUE TITLE
编辑器工具栏支持插入分割线

### ISSUE THREAD

**Issue by TCOTC** [iamqiz/siyuan-plugin-add-shortcut-to-topbar#7]
我想在这里手动插入一条竖线，用于在视觉上分隔常用的和不常用的部分：

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/1d1a5f10-3417-4df4-b903-5237e015d499)

竖线应该能添加和删除（或者预置几条竖线也行）：

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/a8574ca8-b338-4399-ad9c-10c2191a8560)

**Comment by iamqiz** [comment]
v1.1.5 解决

**Comment by TCOTC** [comment]
~~样式能不能像原生的这样：~~ 不对，好像是我主题有问题

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/27b84836-87a4-4791-ad3b-19992f2c0953)

![image](https://github.com/iamqiz/siyuan-plugin-add-shortcut-to-topbar/assets/78434827/81ee6b7f-3310-4da9-a006-22ac35e4db5f)
